FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    python3 \
    python3-libiio \
    python3-numpy \
    python3-matplotlib \
    python3-pil \
    libiio-utils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY sdr_node.py .

CMD ["python3", "sdr_node.py"]
